# Generated by Django 4.0.2 on 2022-03-11 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furniture_app', '0006_alter_product_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(default=None, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='short_description',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Характеристики'),
        ),
    ]
