# Generated by Django 4.0.2 on 2022-03-12 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('furniture_app', '0007_alter_product_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartproduct',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartproduct',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='cartproduct',
            name='user',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartProduct',
        ),
    ]
