# Generated by Django 4.0.2 on 2022-03-12 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('furniture_app', '0008_remove_cartproduct_cart_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создана'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='products_images/', verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активна'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='is_main',
            field=models.BooleanField(default=False, verbose_name='Основная'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='furniture_app.product', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Изменена'),
        ),
    ]
