# Generated by Django 4.0.2 on 2022-03-24 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furniture_app', '0010_remove_customer_address_remove_customer_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, default=None, max_length=254, null=True, verbose_name='Почта'),
        ),
        migrations.AddField(
            model_name='customer',
            name='lastname',
            field=models.CharField(blank=True, default=None, max_length=64, null=True, verbose_name='Фамилия пользователя'),
        ),
        migrations.AddField(
            model_name='customer',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=64, null=True, verbose_name='Имя пользователя'),
        ),
        migrations.AddField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, default=None, max_length=48, null=True, verbose_name='Номер телефона'),
        ),
    ]
