# Generated by Django 4.0.2 on 2022-05-13 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furniture_app', '0011_customer_email_customer_lastname_customer_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='is_additional',
            field=models.BooleanField(default=False, null=True, verbose_name='Дополнительная'),
        ),
    ]
