# Generated by Django 4.0.2 on 2022-05-13 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furniture_app', '0012_productimage_is_additional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='is_additional',
            field=models.BooleanField(default=False, verbose_name='Дополнительная'),
        ),
    ]
