# Generated by Django 4.0.2 on 2022-05-14 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furniture_app', '0013_alter_productimage_is_additional'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='characters',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Характеристики'),
        ),
        migrations.AlterField(
            model_name='product',
            name='short_description',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Краткое описание'),
        ),
    ]
