# Generated by Django 4.0.2 on 2022-06-02 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furniture_app', '0014_product_characters_alter_product_short_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='products_images/main/', verbose_name='Изображение'),
        ),
    ]
