# Generated by Django 4.0.2 on 2022-03-17 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_rename_nmb_productinorder_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productincart',
            name='count',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество'),
        ),
    ]
