# Generated by Django 4.0.2 on 2022-03-24 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_productincart_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_lastname',
            field=models.CharField(blank=True, default=None, max_length=64, null=True, verbose_name='Фамилия пользователя'),
        ),
    ]
