# Generated by Django 4.0.2 on 2022-03-13 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_title', models.CharField(max_length=50, verbose_name='Название проекта')),
                ('image', models.ImageField(upload_to='landing/', verbose_name='Фотография')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Изменена')),
            ],
            options={
                'verbose_name': 'Фотография проектов',
                'verbose_name_plural': 'Фотографии проектов',
            },
        ),
    ]
