# Generated by Django 4.0.2 on 2022-05-14 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=200, verbose_name='Фамилия')),
                ('phone_number', models.CharField(max_length=200, verbose_name='Номер телефона')),
                ('email', models.EmailField(max_length=200, verbose_name='Почта')),
                ('message', models.TextField(max_length=1000, verbose_name='Имя')),
            ],
        ),
    ]
