# Generated by Django 4.0.2 on 2022-05-15 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_contactform'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactform',
            options={'verbose_name': 'Обратная связь', 'verbose_name_plural': 'Обратная связь'},
        ),
        migrations.AlterField(
            model_name='contactform',
            name='message',
            field=models.TextField(max_length=1000, verbose_name='Сообщение'),
        ),
    ]
